"""Cell: flatpmos1x0_3"""
# Auto-generated by split_klayout_cells.py
# Edit geometry here after layer remapping.

import pya

def build_flatpmos1x0_3(cell, L, cells):
    """Populate cell "flatpmos1x0_3" with shapes and sub-cell instances.
    Args:
        cell  – pya.Cell for "flatpmos1x0_3"
        L     – layers namespace from layers.register_layers()
        cells – dict of all cell objects keyed by cell name
    """
