"""Cell: nmos_8x2"""
# Auto-generated by split_klayout_cells.py
# Edit geometry here after layer remapping.
# This cell instantiates: sky130_fd_pr__nfet_01v8_BDGNGK

import pya

def build_nmos_8x2(cell, L, cells):
    """Populate cell "nmos_8x2" with shapes and sub-cell instances.
    Args:
        cell  – pya.Cell for "nmos_8x2"
        L     – layers namespace from layers.register_layers()
        cells – dict of all cell objects keyed by cell name
    """
    cell.insert(pya.DCellInstArray(
        cells["sky130_fd_pr__nfet_01v8_BDGNGK"].cell_index(),
        pya.DCplxTrans(1, 0, False,
                      pya.DVector(1.29, 4.285))))

