"""Cell: reference"""
# Auto-generated by split_klayout_cells.py
# Edit geometry here after layer remapping.
# This cell instantiates: ToBiasStartup, OgueyAebischerBias

import pya

def build_reference(cell, L, cells):
    """Populate cell "reference" with shapes and sub-cell instances.
    Args:
        cell  – pya.Cell for "reference"
        L     – layers namespace from layers.register_layers()
        cells – dict of all cell objects keyed by cell name
    """
    cell.insert(pya.DCellInstArray(
        cells["ToBiasStartup"].cell_index(),
        pya.DCplxTrans(1, 180, True,
                      pya.DVector(-4.06, 0))))
    cell.insert(pya.DCellInstArray(
        cells["OgueyAebischerBias"].cell_index(),
        pya.DCplxTrans(1, 0, False,
                      pya.DVector(0, 0))))
    _txt = pya.Text("vss",
                   pya.Trans(0, False, pya.Vector(-6275, -1290)))
    _txt.halign = 1
    _txt.valign = 1
    cell.shapes(L.L_69_5).insert(_txt)
    cell.shapes(L.L_69_16).insert(
        pya.DPolygon([pya.DPoint(-6.41, -1.42), pya.DPoint(-6.14, -1.42), pya.DPoint(-6.14, -1.16), pya.DPoint(-6.41, -1.16), pya.DPoint(-6.41, -1.42)]))
    _txt = pya.Text("vdd",
                   pya.Trans(0, False, pya.Vector(-6275, 4000)))
    _txt.halign = 1
    _txt.valign = 1
    cell.shapes(L.L_69_5).insert(_txt)
    cell.shapes(L.L_69_16).insert(
        pya.DPolygon([pya.DPoint(-6.41, 3.87), pya.DPoint(-6.14, 3.87), pya.DPoint(-6.14, 4.13), pya.DPoint(-6.41, 4.13), pya.DPoint(-6.41, 3.87)]))
    _txt = pya.Text("vbp",
                   pya.Trans(0, False, pya.Vector(-6275, 1940)))
    _txt.halign = 1
    _txt.valign = 1
    cell.shapes(L.L_69_5).insert(_txt)
    cell.shapes(L.L_69_16).insert(
        pya.DPolygon([pya.DPoint(-6.41, 1.81), pya.DPoint(-6.14, 1.81), pya.DPoint(-6.14, 2.07), pya.DPoint(-6.41, 2.07), pya.DPoint(-6.41, 1.81)]))
    _txt = pya.Text("vbn",
                   pya.Trans(0, False, pya.Vector(-6275, 1540)))
    _txt.halign = 1
    _txt.valign = 1
    cell.shapes(L.L_69_5).insert(_txt)
    cell.shapes(L.L_69_16).insert(
        pya.DPolygon([pya.DPoint(-6.41, 1.41), pya.DPoint(-6.14, 1.41), pya.DPoint(-6.14, 1.67), pya.DPoint(-6.41, 1.67), pya.DPoint(-6.41, 1.41)]))
    _txt = pya.Text("vbr",
                   pya.Trans(0, False, pya.Vector(-6275, 1140)))
    _txt.halign = 1
    _txt.valign = 1
    cell.shapes(L.L_69_5).insert(_txt)
    cell.shapes(L.L_69_16).insert(
        pya.DPolygon([pya.DPoint(-6.41, 1.01), pya.DPoint(-6.14, 1.01), pya.DPoint(-6.14, 1.27), pya.DPoint(-6.41, 1.27), pya.DPoint(-6.41, 1.01)]))
    _txt = pya.Text("disable",
                   pya.Trans(0, False, pya.Vector(-6275, 740)))
    _txt.halign = 1
    _txt.valign = 1
    cell.shapes(L.L_69_5).insert(_txt)
    cell.shapes(L.L_69_16).insert(
        pya.DPolygon([pya.DPoint(-6.41, 0.61), pya.DPoint(-6.14, 0.61), pya.DPoint(-6.14, 0.87), pya.DPoint(-6.41, 0.87), pya.DPoint(-6.41, 0.61)]))

