"""Cell: shortnmos_2x"""
# Auto-generated by split_klayout_cells.py
# Edit geometry here after layer remapping.

import pya

def build_shortnmos_2x(cell, L, cells):
    """Populate cell "shortnmos_2x" with shapes and sub-cell instances.
    Args:
        cell  – pya.Cell for "shortnmos_2x"
        L     – layers namespace from layers.register_layers()
        cells – dict of all cell objects keyed by cell name
    """
    cell.shapes(L.L_65_20).insert(
        pya.DPolygon([pya.DPoint(-1.14, -0.44), pya.DPoint(-0.14, -0.44), pya.DPoint(-0.14, 0.44), pya.DPoint(-1.14, 0.44), pya.DPoint(-1.14, -0.44)]))
    cell.shapes(L.L_65_20).insert(
        pya.DPolygon([pya.DPoint(0.14, -0.44), pya.DPoint(1.14, -0.44), pya.DPoint(1.14, 0.44), pya.DPoint(0.14, 0.44), pya.DPoint(0.14, -0.44)]))
    cell.shapes(L.L_93_44).insert(
        pya.DPolygon([pya.DPoint(-1.265, -0.565), pya.DPoint(1.265, -0.565), pya.DPoint(1.265, 0.565), pya.DPoint(-1.265, 0.565), pya.DPoint(-1.265, -0.565)]))
    cell.shapes(L.L_66_20).insert(
        pya.DPolygon([pya.DPoint(-1.27, -0.15), pya.DPoint(1.27, -0.15), pya.DPoint(1.27, 0.15), pya.DPoint(-1.27, 0.15), pya.DPoint(-1.27, -0.15)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(-1.065, 0.21), pya.DPoint(-0.895, 0.21), pya.DPoint(-0.895, 0.38), pya.DPoint(-1.065, 0.38), pya.DPoint(-1.065, 0.21)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(-0.725, 0.21), pya.DPoint(-0.555, 0.21), pya.DPoint(-0.555, 0.38), pya.DPoint(-0.725, 0.38), pya.DPoint(-0.725, 0.21)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(-0.385, 0.21), pya.DPoint(-0.215, 0.21), pya.DPoint(-0.215, 0.38), pya.DPoint(-0.385, 0.38), pya.DPoint(-0.385, 0.21)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(0.215, 0.21), pya.DPoint(0.385, 0.21), pya.DPoint(0.385, 0.38), pya.DPoint(0.215, 0.38), pya.DPoint(0.215, 0.21)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(0.555, 0.21), pya.DPoint(0.725, 0.21), pya.DPoint(0.725, 0.38), pya.DPoint(0.555, 0.38), pya.DPoint(0.555, 0.21)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(0.895, 0.21), pya.DPoint(1.065, 0.21), pya.DPoint(1.065, 0.38), pya.DPoint(0.895, 0.38), pya.DPoint(0.895, 0.21)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(-1.065, -0.38), pya.DPoint(-0.895, -0.38), pya.DPoint(-0.895, -0.21), pya.DPoint(-1.065, -0.21), pya.DPoint(-1.065, -0.38)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(-0.725, -0.38), pya.DPoint(-0.555, -0.38), pya.DPoint(-0.555, -0.21), pya.DPoint(-0.725, -0.21), pya.DPoint(-0.725, -0.38)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(-0.385, -0.38), pya.DPoint(-0.215, -0.38), pya.DPoint(-0.215, -0.21), pya.DPoint(-0.385, -0.21), pya.DPoint(-0.385, -0.38)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(0.215, -0.38), pya.DPoint(0.385, -0.38), pya.DPoint(0.385, -0.21), pya.DPoint(0.215, -0.21), pya.DPoint(0.215, -0.38)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(0.555, -0.38), pya.DPoint(0.725, -0.38), pya.DPoint(0.725, -0.21), pya.DPoint(0.555, -0.21), pya.DPoint(0.555, -0.38)]))
    cell.shapes(L.L_66_44).insert(
        pya.DPolygon([pya.DPoint(0.895, -0.38), pya.DPoint(1.065, -0.38), pya.DPoint(1.065, -0.21), pya.DPoint(0.895, -0.21), pya.DPoint(0.895, -0.38)]))
    cell.shapes(L.L_67_20).insert(
        pya.DPolygon([pya.DPoint(-1.16, 0.21), pya.DPoint(-0.12, 0.21), pya.DPoint(-0.12, 0.38), pya.DPoint(-1.16, 0.38), pya.DPoint(-1.16, 0.21)]))
    cell.shapes(L.L_67_20).insert(
        pya.DPolygon([pya.DPoint(0.12, 0.21), pya.DPoint(1.16, 0.21), pya.DPoint(1.16, 0.38), pya.DPoint(0.12, 0.38), pya.DPoint(0.12, 0.21)]))
    cell.shapes(L.L_67_20).insert(
        pya.DPolygon([pya.DPoint(-1.16, -0.38), pya.DPoint(1.16, -0.38), pya.DPoint(1.16, -0.21), pya.DPoint(-1.16, -0.21), pya.DPoint(-1.16, -0.38)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(-0.905, 0.21), pya.DPoint(-0.735, 0.21), pya.DPoint(-0.735, 0.38), pya.DPoint(-0.905, 0.38), pya.DPoint(-0.905, 0.21)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(-0.545, 0.21), pya.DPoint(-0.375, 0.21), pya.DPoint(-0.375, 0.38), pya.DPoint(-0.545, 0.38), pya.DPoint(-0.545, 0.21)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(0.375, 0.21), pya.DPoint(0.545, 0.21), pya.DPoint(0.545, 0.38), pya.DPoint(0.375, 0.38), pya.DPoint(0.375, 0.21)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(0.735, 0.21), pya.DPoint(0.905, 0.21), pya.DPoint(0.905, 0.38), pya.DPoint(0.735, 0.38), pya.DPoint(0.735, 0.21)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(-0.905, -0.38), pya.DPoint(-0.735, -0.38), pya.DPoint(-0.735, -0.21), pya.DPoint(-0.905, -0.21), pya.DPoint(-0.905, -0.38)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(-0.545, -0.38), pya.DPoint(-0.375, -0.38), pya.DPoint(-0.375, -0.21), pya.DPoint(-0.545, -0.21), pya.DPoint(-0.545, -0.38)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(0.375, -0.38), pya.DPoint(0.545, -0.38), pya.DPoint(0.545, -0.21), pya.DPoint(0.375, -0.21), pya.DPoint(0.375, -0.38)]))
    cell.shapes(L.L_67_44).insert(
        pya.DPolygon([pya.DPoint(0.735, -0.38), pya.DPoint(0.905, -0.38), pya.DPoint(0.905, -0.21), pya.DPoint(0.735, -0.21), pya.DPoint(0.735, -0.38)]))
    cell.shapes(L.L_68_20).insert(
        pya.DPolygon([pya.DPoint(-1.14, 0.18), pya.DPoint(-0.14, 0.18), pya.DPoint(-0.14, 0.41), pya.DPoint(-1.14, 0.41), pya.DPoint(-1.14, 0.18)]))
    cell.shapes(L.L_68_20).insert(
        pya.DPolygon([pya.DPoint(0.14, 0.18), pya.DPoint(1.14, 0.18), pya.DPoint(1.14, 0.41), pya.DPoint(0.14, 0.41), pya.DPoint(0.14, 0.18)]))
    cell.shapes(L.L_68_20).insert(
        pya.DPolygon([pya.DPoint(-1.14, -0.41), pya.DPoint(1.14, -0.41), pya.DPoint(1.14, -0.18), pya.DPoint(-1.14, -0.18), pya.DPoint(-1.14, -0.41)]))

