"""Cell: sky130_fd_pr__nfet_01v8_BDGNGK"""
# Auto-generated by split_klayout_cells.py
# Edit geometry here after layer remapping.

import pya

def build_sky130_fd_pr__nfet_01v8_BDGNGK(cell, L, cells):
    """Populate cell "sky130_fd_pr__nfet_01v8_BDGNGK" with shapes and sub-cell instances.
    Args:
        cell  – pya.Cell for "sky130_fd_pr__nfet_01v8_BDGNGK"
        L     – layers namespace from layers.register_layers()
        cells – dict of all cell objects keyed by cell name
    """
    cell.shapes(L.L_diff_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.29, -4.155), pya.DPoint(1.29, -4.155), pya.DPoint(1.29, 3.845), pya.DPoint(-1.29, 3.845), pya.DPoint(-1.29, -4.155)]))
    cell.shapes(L.L_nsdm_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.415, -4.28), pya.DPoint(1.415, -4.28), pya.DPoint(1.415, 3.97), pya.DPoint(-1.415, 3.97), pya.DPoint(-1.415, -4.28)]))
    cell.shapes(L.L_poly_drawing).insert(
        pya.DPolygon([pya.DPoint(-1, -4.285), pya.DPoint(1, -4.285), pya.DPoint(1, 4.285), pya.DPoint(-1, 4.285), pya.DPoint(-1, -4.285)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.765, 4.035), pya.DPoint(-0.595, 4.035), pya.DPoint(-0.595, 4.205), pya.DPoint(-0.765, 4.205), pya.DPoint(-0.765, 4.035)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.425, 4.035), pya.DPoint(-0.255, 4.035), pya.DPoint(-0.255, 4.205), pya.DPoint(-0.425, 4.205), pya.DPoint(-0.425, 4.035)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.085, 4.035), pya.DPoint(0.085, 4.035), pya.DPoint(0.085, 4.205), pya.DPoint(-0.085, 4.205), pya.DPoint(-0.085, 4.035)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(0.255, 4.035), pya.DPoint(0.425, 4.035), pya.DPoint(0.425, 4.205), pya.DPoint(0.255, 4.205), pya.DPoint(0.255, 4.035)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(0.595, 4.035), pya.DPoint(0.765, 4.035), pya.DPoint(0.765, 4.205), pya.DPoint(0.595, 4.205), pya.DPoint(0.595, 4.035)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 3.5), pya.DPoint(-1.06, 3.5), pya.DPoint(-1.06, 3.67), pya.DPoint(-1.23, 3.67), pya.DPoint(-1.23, 3.5)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 3.5), pya.DPoint(1.23, 3.5), pya.DPoint(1.23, 3.67), pya.DPoint(1.06, 3.67), pya.DPoint(1.06, 3.5)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 3.16), pya.DPoint(-1.06, 3.16), pya.DPoint(-1.06, 3.33), pya.DPoint(-1.23, 3.33), pya.DPoint(-1.23, 3.16)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 3.16), pya.DPoint(1.23, 3.16), pya.DPoint(1.23, 3.33), pya.DPoint(1.06, 3.33), pya.DPoint(1.06, 3.16)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 2.82), pya.DPoint(-1.06, 2.82), pya.DPoint(-1.06, 2.99), pya.DPoint(-1.23, 2.99), pya.DPoint(-1.23, 2.82)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 2.82), pya.DPoint(1.23, 2.82), pya.DPoint(1.23, 2.99), pya.DPoint(1.06, 2.99), pya.DPoint(1.06, 2.82)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 2.48), pya.DPoint(-1.06, 2.48), pya.DPoint(-1.06, 2.65), pya.DPoint(-1.23, 2.65), pya.DPoint(-1.23, 2.48)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 2.48), pya.DPoint(1.23, 2.48), pya.DPoint(1.23, 2.65), pya.DPoint(1.06, 2.65), pya.DPoint(1.06, 2.48)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 2.14), pya.DPoint(-1.06, 2.14), pya.DPoint(-1.06, 2.31), pya.DPoint(-1.23, 2.31), pya.DPoint(-1.23, 2.14)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 2.14), pya.DPoint(1.23, 2.14), pya.DPoint(1.23, 2.31), pya.DPoint(1.06, 2.31), pya.DPoint(1.06, 2.14)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 1.8), pya.DPoint(-1.06, 1.8), pya.DPoint(-1.06, 1.97), pya.DPoint(-1.23, 1.97), pya.DPoint(-1.23, 1.8)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 1.8), pya.DPoint(1.23, 1.8), pya.DPoint(1.23, 1.97), pya.DPoint(1.06, 1.97), pya.DPoint(1.06, 1.8)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 1.46), pya.DPoint(-1.06, 1.46), pya.DPoint(-1.06, 1.63), pya.DPoint(-1.23, 1.63), pya.DPoint(-1.23, 1.46)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 1.46), pya.DPoint(1.23, 1.46), pya.DPoint(1.23, 1.63), pya.DPoint(1.06, 1.63), pya.DPoint(1.06, 1.46)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 1.12), pya.DPoint(-1.06, 1.12), pya.DPoint(-1.06, 1.29), pya.DPoint(-1.23, 1.29), pya.DPoint(-1.23, 1.12)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 1.12), pya.DPoint(1.23, 1.12), pya.DPoint(1.23, 1.29), pya.DPoint(1.06, 1.29), pya.DPoint(1.06, 1.12)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 0.78), pya.DPoint(-1.06, 0.78), pya.DPoint(-1.06, 0.95), pya.DPoint(-1.23, 0.95), pya.DPoint(-1.23, 0.78)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 0.78), pya.DPoint(1.23, 0.78), pya.DPoint(1.23, 0.95), pya.DPoint(1.06, 0.95), pya.DPoint(1.06, 0.78)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 0.44), pya.DPoint(-1.06, 0.44), pya.DPoint(-1.06, 0.61), pya.DPoint(-1.23, 0.61), pya.DPoint(-1.23, 0.44)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 0.44), pya.DPoint(1.23, 0.44), pya.DPoint(1.23, 0.61), pya.DPoint(1.06, 0.61), pya.DPoint(1.06, 0.44)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 0.1), pya.DPoint(-1.06, 0.1), pya.DPoint(-1.06, 0.27), pya.DPoint(-1.23, 0.27), pya.DPoint(-1.23, 0.1)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 0.1), pya.DPoint(1.23, 0.1), pya.DPoint(1.23, 0.27), pya.DPoint(1.06, 0.27), pya.DPoint(1.06, 0.1)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -0.24), pya.DPoint(-1.06, -0.24), pya.DPoint(-1.06, -0.07), pya.DPoint(-1.23, -0.07), pya.DPoint(-1.23, -0.24)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -0.24), pya.DPoint(1.23, -0.24), pya.DPoint(1.23, -0.07), pya.DPoint(1.06, -0.07), pya.DPoint(1.06, -0.24)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -0.58), pya.DPoint(-1.06, -0.58), pya.DPoint(-1.06, -0.41), pya.DPoint(-1.23, -0.41), pya.DPoint(-1.23, -0.58)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -0.58), pya.DPoint(1.23, -0.58), pya.DPoint(1.23, -0.41), pya.DPoint(1.06, -0.41), pya.DPoint(1.06, -0.58)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -0.92), pya.DPoint(-1.06, -0.92), pya.DPoint(-1.06, -0.75), pya.DPoint(-1.23, -0.75), pya.DPoint(-1.23, -0.92)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -0.92), pya.DPoint(1.23, -0.92), pya.DPoint(1.23, -0.75), pya.DPoint(1.06, -0.75), pya.DPoint(1.06, -0.92)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -1.26), pya.DPoint(-1.06, -1.26), pya.DPoint(-1.06, -1.09), pya.DPoint(-1.23, -1.09), pya.DPoint(-1.23, -1.26)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -1.26), pya.DPoint(1.23, -1.26), pya.DPoint(1.23, -1.09), pya.DPoint(1.06, -1.09), pya.DPoint(1.06, -1.26)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -1.6), pya.DPoint(-1.06, -1.6), pya.DPoint(-1.06, -1.43), pya.DPoint(-1.23, -1.43), pya.DPoint(-1.23, -1.6)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -1.6), pya.DPoint(1.23, -1.6), pya.DPoint(1.23, -1.43), pya.DPoint(1.06, -1.43), pya.DPoint(1.06, -1.6)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -1.94), pya.DPoint(-1.06, -1.94), pya.DPoint(-1.06, -1.77), pya.DPoint(-1.23, -1.77), pya.DPoint(-1.23, -1.94)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -1.94), pya.DPoint(1.23, -1.94), pya.DPoint(1.23, -1.77), pya.DPoint(1.06, -1.77), pya.DPoint(1.06, -1.94)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -2.28), pya.DPoint(-1.06, -2.28), pya.DPoint(-1.06, -2.11), pya.DPoint(-1.23, -2.11), pya.DPoint(-1.23, -2.28)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -2.28), pya.DPoint(1.23, -2.28), pya.DPoint(1.23, -2.11), pya.DPoint(1.06, -2.11), pya.DPoint(1.06, -2.28)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -2.62), pya.DPoint(-1.06, -2.62), pya.DPoint(-1.06, -2.45), pya.DPoint(-1.23, -2.45), pya.DPoint(-1.23, -2.62)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -2.62), pya.DPoint(1.23, -2.62), pya.DPoint(1.23, -2.45), pya.DPoint(1.06, -2.45), pya.DPoint(1.06, -2.62)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -2.96), pya.DPoint(-1.06, -2.96), pya.DPoint(-1.06, -2.79), pya.DPoint(-1.23, -2.79), pya.DPoint(-1.23, -2.96)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -2.96), pya.DPoint(1.23, -2.96), pya.DPoint(1.23, -2.79), pya.DPoint(1.06, -2.79), pya.DPoint(1.06, -2.96)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -3.3), pya.DPoint(-1.06, -3.3), pya.DPoint(-1.06, -3.13), pya.DPoint(-1.23, -3.13), pya.DPoint(-1.23, -3.3)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -3.3), pya.DPoint(1.23, -3.3), pya.DPoint(1.23, -3.13), pya.DPoint(1.06, -3.13), pya.DPoint(1.06, -3.3)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -3.64), pya.DPoint(-1.06, -3.64), pya.DPoint(-1.06, -3.47), pya.DPoint(-1.23, -3.47), pya.DPoint(-1.23, -3.64)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -3.64), pya.DPoint(1.23, -3.64), pya.DPoint(1.23, -3.47), pya.DPoint(1.06, -3.47), pya.DPoint(1.06, -3.64)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -3.98), pya.DPoint(-1.06, -3.98), pya.DPoint(-1.06, -3.81), pya.DPoint(-1.23, -3.81), pya.DPoint(-1.23, -3.98)]))
    cell.shapes(L.L_licon1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -3.98), pya.DPoint(1.23, -3.98), pya.DPoint(1.23, -3.81), pya.DPoint(1.06, -3.81), pya.DPoint(1.06, -3.98)]))
    cell.shapes(L.L_npc_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.865, 3.935), pya.DPoint(0.865, 3.935), pya.DPoint(0.865, 4.305), pya.DPoint(-0.865, 4.305), pya.DPoint(-0.865, 3.935)]))
    cell.shapes(L.L_li1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1, 4.035), pya.DPoint(1, 4.035), pya.DPoint(1, 4.205), pya.DPoint(-1, 4.205), pya.DPoint(-1, 4.035)]))
    cell.shapes(L.L_li1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -4.175), pya.DPoint(-1.06, -4.175), pya.DPoint(-1.06, 3.865), pya.DPoint(-1.23, 3.865), pya.DPoint(-1.23, -4.175)]))
    cell.shapes(L.L_li1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -4.175), pya.DPoint(1.23, -4.175), pya.DPoint(1.23, 3.865), pya.DPoint(1.06, 3.865), pya.DPoint(1.06, -4.175)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.805, 4.035), pya.DPoint(-0.635, 4.035), pya.DPoint(-0.635, 4.205), pya.DPoint(-0.805, 4.205), pya.DPoint(-0.805, 4.035)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.445, 4.035), pya.DPoint(-0.275, 4.035), pya.DPoint(-0.275, 4.205), pya.DPoint(-0.445, 4.205), pya.DPoint(-0.445, 4.035)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.085, 4.035), pya.DPoint(0.085, 4.035), pya.DPoint(0.085, 4.205), pya.DPoint(-0.085, 4.205), pya.DPoint(-0.085, 4.035)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(0.275, 4.035), pya.DPoint(0.445, 4.035), pya.DPoint(0.445, 4.205), pya.DPoint(0.275, 4.205), pya.DPoint(0.275, 4.035)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(0.635, 4.035), pya.DPoint(0.805, 4.035), pya.DPoint(0.805, 4.205), pya.DPoint(0.635, 4.205), pya.DPoint(0.635, 4.035)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 3.54), pya.DPoint(-1.06, 3.54), pya.DPoint(-1.06, 3.71), pya.DPoint(-1.23, 3.71), pya.DPoint(-1.23, 3.54)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 3.54), pya.DPoint(1.23, 3.54), pya.DPoint(1.23, 3.71), pya.DPoint(1.06, 3.71), pya.DPoint(1.06, 3.54)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 3.18), pya.DPoint(-1.06, 3.18), pya.DPoint(-1.06, 3.35), pya.DPoint(-1.23, 3.35), pya.DPoint(-1.23, 3.18)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 3.18), pya.DPoint(1.23, 3.18), pya.DPoint(1.23, 3.35), pya.DPoint(1.06, 3.35), pya.DPoint(1.06, 3.18)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 2.82), pya.DPoint(-1.06, 2.82), pya.DPoint(-1.06, 2.99), pya.DPoint(-1.23, 2.99), pya.DPoint(-1.23, 2.82)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 2.82), pya.DPoint(1.23, 2.82), pya.DPoint(1.23, 2.99), pya.DPoint(1.06, 2.99), pya.DPoint(1.06, 2.82)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 2.46), pya.DPoint(-1.06, 2.46), pya.DPoint(-1.06, 2.63), pya.DPoint(-1.23, 2.63), pya.DPoint(-1.23, 2.46)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 2.46), pya.DPoint(1.23, 2.46), pya.DPoint(1.23, 2.63), pya.DPoint(1.06, 2.63), pya.DPoint(1.06, 2.46)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 2.1), pya.DPoint(-1.06, 2.1), pya.DPoint(-1.06, 2.27), pya.DPoint(-1.23, 2.27), pya.DPoint(-1.23, 2.1)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 2.1), pya.DPoint(1.23, 2.1), pya.DPoint(1.23, 2.27), pya.DPoint(1.06, 2.27), pya.DPoint(1.06, 2.1)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 1.74), pya.DPoint(-1.06, 1.74), pya.DPoint(-1.06, 1.91), pya.DPoint(-1.23, 1.91), pya.DPoint(-1.23, 1.74)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 1.74), pya.DPoint(1.23, 1.74), pya.DPoint(1.23, 1.91), pya.DPoint(1.06, 1.91), pya.DPoint(1.06, 1.74)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 1.38), pya.DPoint(-1.06, 1.38), pya.DPoint(-1.06, 1.55), pya.DPoint(-1.23, 1.55), pya.DPoint(-1.23, 1.38)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 1.38), pya.DPoint(1.23, 1.38), pya.DPoint(1.23, 1.55), pya.DPoint(1.06, 1.55), pya.DPoint(1.06, 1.38)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 1.02), pya.DPoint(-1.06, 1.02), pya.DPoint(-1.06, 1.19), pya.DPoint(-1.23, 1.19), pya.DPoint(-1.23, 1.02)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 1.02), pya.DPoint(1.23, 1.02), pya.DPoint(1.23, 1.19), pya.DPoint(1.06, 1.19), pya.DPoint(1.06, 1.02)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 0.66), pya.DPoint(-1.06, 0.66), pya.DPoint(-1.06, 0.83), pya.DPoint(-1.23, 0.83), pya.DPoint(-1.23, 0.66)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 0.66), pya.DPoint(1.23, 0.66), pya.DPoint(1.23, 0.83), pya.DPoint(1.06, 0.83), pya.DPoint(1.06, 0.66)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, 0.3), pya.DPoint(-1.06, 0.3), pya.DPoint(-1.06, 0.47), pya.DPoint(-1.23, 0.47), pya.DPoint(-1.23, 0.3)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, 0.3), pya.DPoint(1.23, 0.3), pya.DPoint(1.23, 0.47), pya.DPoint(1.06, 0.47), pya.DPoint(1.06, 0.3)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -0.06), pya.DPoint(-1.06, -0.06), pya.DPoint(-1.06, 0.11), pya.DPoint(-1.23, 0.11), pya.DPoint(-1.23, -0.06)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -0.06), pya.DPoint(1.23, -0.06), pya.DPoint(1.23, 0.11), pya.DPoint(1.06, 0.11), pya.DPoint(1.06, -0.06)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -0.42), pya.DPoint(-1.06, -0.42), pya.DPoint(-1.06, -0.25), pya.DPoint(-1.23, -0.25), pya.DPoint(-1.23, -0.42)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -0.42), pya.DPoint(1.23, -0.42), pya.DPoint(1.23, -0.25), pya.DPoint(1.06, -0.25), pya.DPoint(1.06, -0.42)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -0.78), pya.DPoint(-1.06, -0.78), pya.DPoint(-1.06, -0.61), pya.DPoint(-1.23, -0.61), pya.DPoint(-1.23, -0.78)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -0.78), pya.DPoint(1.23, -0.78), pya.DPoint(1.23, -0.61), pya.DPoint(1.06, -0.61), pya.DPoint(1.06, -0.78)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -1.14), pya.DPoint(-1.06, -1.14), pya.DPoint(-1.06, -0.97), pya.DPoint(-1.23, -0.97), pya.DPoint(-1.23, -1.14)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -1.14), pya.DPoint(1.23, -1.14), pya.DPoint(1.23, -0.97), pya.DPoint(1.06, -0.97), pya.DPoint(1.06, -1.14)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -1.5), pya.DPoint(-1.06, -1.5), pya.DPoint(-1.06, -1.33), pya.DPoint(-1.23, -1.33), pya.DPoint(-1.23, -1.5)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -1.5), pya.DPoint(1.23, -1.5), pya.DPoint(1.23, -1.33), pya.DPoint(1.06, -1.33), pya.DPoint(1.06, -1.5)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -1.86), pya.DPoint(-1.06, -1.86), pya.DPoint(-1.06, -1.69), pya.DPoint(-1.23, -1.69), pya.DPoint(-1.23, -1.86)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -1.86), pya.DPoint(1.23, -1.86), pya.DPoint(1.23, -1.69), pya.DPoint(1.06, -1.69), pya.DPoint(1.06, -1.86)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -2.22), pya.DPoint(-1.06, -2.22), pya.DPoint(-1.06, -2.05), pya.DPoint(-1.23, -2.05), pya.DPoint(-1.23, -2.22)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -2.22), pya.DPoint(1.23, -2.22), pya.DPoint(1.23, -2.05), pya.DPoint(1.06, -2.05), pya.DPoint(1.06, -2.22)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -2.58), pya.DPoint(-1.06, -2.58), pya.DPoint(-1.06, -2.41), pya.DPoint(-1.23, -2.41), pya.DPoint(-1.23, -2.58)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -2.58), pya.DPoint(1.23, -2.58), pya.DPoint(1.23, -2.41), pya.DPoint(1.06, -2.41), pya.DPoint(1.06, -2.58)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -2.94), pya.DPoint(-1.06, -2.94), pya.DPoint(-1.06, -2.77), pya.DPoint(-1.23, -2.77), pya.DPoint(-1.23, -2.94)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -2.94), pya.DPoint(1.23, -2.94), pya.DPoint(1.23, -2.77), pya.DPoint(1.06, -2.77), pya.DPoint(1.06, -2.94)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -3.3), pya.DPoint(-1.06, -3.3), pya.DPoint(-1.06, -3.13), pya.DPoint(-1.23, -3.13), pya.DPoint(-1.23, -3.3)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -3.3), pya.DPoint(1.23, -3.3), pya.DPoint(1.23, -3.13), pya.DPoint(1.06, -3.13), pya.DPoint(1.06, -3.3)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -3.66), pya.DPoint(-1.06, -3.66), pya.DPoint(-1.06, -3.49), pya.DPoint(-1.23, -3.49), pya.DPoint(-1.23, -3.66)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -3.66), pya.DPoint(1.23, -3.66), pya.DPoint(1.23, -3.49), pya.DPoint(1.06, -3.49), pya.DPoint(1.06, -3.66)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.23, -4.02), pya.DPoint(-1.06, -4.02), pya.DPoint(-1.06, -3.85), pya.DPoint(-1.23, -3.85), pya.DPoint(-1.23, -4.02)]))
    cell.shapes(L.L_mcon_drawing).insert(
        pya.DPolygon([pya.DPoint(1.06, -4.02), pya.DPoint(1.23, -4.02), pya.DPoint(1.23, -3.85), pya.DPoint(1.06, -3.85), pya.DPoint(1.06, -4.02)]))
    cell.shapes(L.L_met1_drawing).insert(
        pya.DPolygon([pya.DPoint(-0.98, 4.005), pya.DPoint(0.98, 4.005), pya.DPoint(0.98, 4.235), pya.DPoint(-0.98, 4.235), pya.DPoint(-0.98, 4.005)]))
    cell.shapes(L.L_met1_drawing).insert(
        pya.DPolygon([pya.DPoint(-1.26, -4.155), pya.DPoint(-1.03, -4.155), pya.DPoint(-1.03, 3.845), pya.DPoint(-1.26, 3.845), pya.DPoint(-1.26, -4.155)]))
    cell.shapes(L.L_met1_drawing).insert(
        pya.DPolygon([pya.DPoint(1.03, -4.155), pya.DPoint(1.26, -4.155), pya.DPoint(1.26, 3.845), pya.DPoint(1.03, 3.845), pya.DPoint(1.03, -4.155)]))

